package yurit

const (
	AlwaysMinus2Key        = "alwaysMinus2"
	Always0Key             = "always0"
	Always3Key             = "always3"
	Always16Key            = "always16"
	Always65536Key         = "always65536"
	Always7F000000Key      = "always7F000000"
	AverageBitrateKey      = "averageBitrate"
	BytesPerFrameKey       = "bytesPerFrame"
	BytesPerPacketKey      = "bytesPerPacket"
	BytesPerSampleKey      = "bytesPerSample"
	ChannelsKey            = "channels"
	CompatibleBrandsKey    = "compatibleBrands"
	CompressionKey         = "compression"
	ConstBitsPerChannelKey = "constBitsPerChannel"
	ConstBytesPerPacket    = "constBytesPerPacket"
	ConstFramesPerPacket   = "constFramesPerPacket"
	DurationKey            = "duration"
	FlagsKey               = "flags"
	LPCMFlagsKey           = "lpcmFlags"
	MajorBrandKey          = "majorBrand"
	MaximumBitrateKey      = "maximumBitrate"
	MaximumBlockSizeKey    = "maximumBlockSize"
	MaximumFrameSizeKey    = "maximumFrameSize"
	MD5Key                 = "md5"
	MinimumBitrateKey      = "minimumBitrate"
	MinimumBlockSizeKey    = "minimumBlockSize"
	MinimumFrameSizeKey    = "minimumFrameSize"
	MinorVersionKey        = "minorVersion"
	PacketSizeKey          = "packetSize"
	RevisionKey            = "revision"
	SampleRateKey          = "sampleRate"
	SampleSizeKey          = "sampleSize"
	SamplesPerPacketKey    = "samplesPerPacket"
	SizeOfStructOnlyKey    = "sizeOfStructOnly"
	TimeScaleKey           = "timeScale"
	TotalSamplesKey        = "totalSamples"
	VendorKey              = "vendor"
	VersionKey             = "version"
)
